plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.14'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.focuz'
version = '0.0.1-SNAPSHOT'
description = 'auth-service'

def env = rootProject.file(".env")
if(env.exists()) {
    env.eachLine {
        l -> {
            if(l.contains("=")) {
                def line = l.split("=", 2)
                System.setProperty(line[0].trim(), line[1].trim())
            }
        }
    }
}
def GIT_USERNAME = System.getProperty("GIT_USERNAME")
def GIT_PASSWORD = System.getProperty("GIT_TOKEN")

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

ext {
    set('springCloudVersion', "2025.0.2")
    set("encryptionStarterVersion", property("ENCRYPTION_STARTER_VERSION"))
    set("coreStarterVersion", property("CORE_STARTER_VERSION"))
    set("iscStarterVersion", property("ISC_STARTER_VERSION"))
}

repositories {
    mavenCentral()
    maven {
        name="GitHubPackage"
        url=uri("https://maven.pkg.github.com/JAMIES-TRAN/focuz")
        credentials{
            username=GIT_USERNAME
            password=GIT_PASSWORD
        }
    }
}

dependencies {
    implementation "com.focuz:encryption-starter:${encryptionStarterVersion}"
    implementation "com.focuz:core-starter:${coreStarterVersion}"
    implementation "com.focuz:isc-starter:${iscStarterVersion}"
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'org.springframework.boot:spring-boot-starter-validation:4.1.0-M4'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
    runtimeOnly 'com.mysql:mysql-connector-j'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
