spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://focuz-db-dev:3306/auth
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
      host: focuz-cache-dev
      timeout: 60000


eureka:
  client:
    service-url:
      defaultZone: http://discovery-dev:8761/eureka

environment:
  authenticationCode:
    ttl: 300000

encryption:
  pubKey: MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAn2ClUYxFEg/8C/k5DDIGUYuFcwM5NarNw+7tcWhKK2MMKjVO7WnblCmQSACRPyTZ/MMwaMnN4KjJKF15UiU7e65VGZD0286rswvbuOte4mQSOpv51mjRMU87f94vW2edsQb7lLe4UopV3VDReqrcHczncb6fMdr1VMuabUMepiAwpbLsiDBOG1FJU+UsGUkoMomUvQdKEUf78UAz7IuopzpQf2rstqiTY4c4pZuXL9Bo+QPIEzWWfbQqY+tDFocWHwEDKiqUmaiyx4kWaFW25Fe0l+RaQxaWXr1MRw9a0yikdeHNzAorwPVHRfChDw+H5MzahD0q+3iXmR6uWH3AcFc7ugkcPvQdu4i0A0mJx9LBXEVChpop3zdKVXcQs/mL1dmPH4nKGm5ii1RPupwR01tK99GiBNm9ICkAauACPju3+sCrdpDTIg/R0srdAfum6CIwIE5qiFaZUE8oepB/dZaLZmMbWe0nWiiGbRAK48cxAKa7cGMORX+xV7u309nvAgMBAAE=
  priKey: MIIG/AIBADANBgkqhkiG9w0BAQEFAASCBuYwggbiAgEAAoIBgQCfYKVRjEUSD/wL+TkMMgZRi4VzAzk1qs3D7u1xaEorYwwqNU7taduUKZBIAJE/JNn8wzBoyc3gqMkoXXlSJTt7rlUZkPTbzquzC9u4617iZBI6m/nWaNExTzt/3i9bZ52xBvuUt7hSilXdUNF6qtwdzOdxvp8x2vVUy5ptQx6mIDClsuyIME4bUUlT5SwZSSgyiZS9B0oRR/vxQDPsi6inOlB/auy2qJNjhzilm5cv0Gj5A8gTNZZ9tCpj60MWhxYfAQMqKpSZqLLHiRZoVbbkV7SX5FpDFpZevUxHD1rTKKR14c3MCivA9UdF8KEPD4fkzNqEPSr7eJeZHq5YfcBwVzu6CRw+9B27iLQDSYnH0sFcRUKGminfN0pVdxCz+YvV2Y8ficoabmKLVE+6nBHTW0r30aIE2b0gKQBq4AI+O7f6wKt2kNMiD9HSyt0B+6boIjAgTmqIVplQTyh6kH91lotmYxtZ7SdaKIZtEArjxzEAprtwYw5Ff7FXu7fT2e8CAwEAAQKCAYAtaapxjBh6Rxe4ibEZqn9maO0Dkp2QjzTGaaQ6tk68AiMLO9lbiNhKZXV5LsA0T9nVTgDTOv1w0GdRGyFgqL9ERK529Hjw0PjXsb9P97E3rPAMxzjvQTqqZDs9+h9gWivyr1ysSZU537ULtOWboGfMDgC8xmYyHIPfP4ynKYLoLy/tZwhC3hDDc+wC/cANDG1pyQ4atqMCPZKqcXLaKglKbTFWvS7p9SraJ0Oa3LS9qRLgMZWm85QICXgytGyPVLojoZHFsd/ilauQ+ncPAGZztGsilFns+droN/HsEv7EyBrD3hB4NtxfvN/7JAwRz55VpUj2wNQqWfZ7/oOhmcsUGN5GqNmn/Twi5xj+4/vvV/osmllBjNl5NRM4Hfk6e1TzVORMuyr4WlZ5OKwDrcNqEqAlpZmR6L1gY2B9ZHPqS9oaa6iwdadowSRf69GvDxnAzynZahBTS0Y7xqLa63cTTLMd1ZmXRh/SBhbVBNhT9+MlQPlOioQK76IUz7ZnU5ECgcEAv5ctESFuOz/ou1HHPn0NlBN85xs1aZyrhk4Kn9POfvXA3/j26MiZyDlfkg+BQq08Wlw8BhcPhrPL92G5ngHl5MOZjII++bj9UmPSxv5NhiTmHT/uKdPCZX6CjzkwOk21BtntcejZvolrOJjYXwCbXwI3TgPGl8M5OL2j0cA1xZqwbdJ2HY1UC2aHE1B4Iyj10QGkgNJuNR71/2vRGdZKvvqG1mVmJUSf4hQHOjodXH9b+2g7DbJNlGbiKJAx+xjFAoHBANT1IH4MOfdaF1tl8kd+DZQ5KBqEC04rXfHByDg0ko5I/nSV5VxJmHYgOw1z9RVY1X1k7kct05Pw5jNCExQQzidkjVHB+Qh9AoX/gsECkR+1rVdAQJh2TYKR+nQb6kjcIS8ZoPFwsAsah3bvfQBIGP1MoEkT3ZJKJxtPmlUdekovu9Gdh66GaxFjt7EUwvvR/sQl9xC/mfx5EDR/q0FGVp5gDKS1hk8s3CIZXZG0ps6JWGsZgdhlwcvHZFS8N6MLIwKBwAxmqqIbOdlX76aASpc+3Owivsjut+xYGbodvw5NVWZeXdehc8npghq1q/v2SPWZ5PgsVC5Iu9aKOL+QccVKdijyiDPSEmVzleIJWBFNUJNIPCTUiIPokwKix6yhlP+RHBCPdpES81Uj6+7D5e1wSp5BtHa2Q9p65m9HxxzChjh+JMFXCBItna0HO+MCKGSOOCsJIi68cCm8EUwxHF3BwyDNcoDaG1x6LqchiL46GMBt9fQ18OyYB/F9H1Jk0vdfyQKBwE4zXaUr1DVyzdTwUNHUBiSCAKoMByLDZhIa+O060P6S623ghYMoO2ZVW5oLFNqr7mnHoIBe4a0X71CvWNYrfaiVkheNxWdKkJyoQVmjGautSWQa4h2ag8gI1xHAFn5+52imXqWKnfrV2RzhwONTlmmds9ZiByFrPYUX7DKJSpjngm7tDCAYmESge5n5Z8iVSpq43ks2MNO3mS3OHBMyQyiRWNM7HYEBliynZ+bTkdWSNffOPBI8+7dbFwrOuxeSRQKBwHmxZuadFvK7YOZuW+pdksLbwOgtHh2nAoBpDm/6Hc4XIBgZCxeH3prkrJOsRNjSy5jSiomcVMMNgRp2XrEqpxUU8ik8wt4i65YcNhel/8hMi7GBlZVQWTwuTHvHZBLJvm1ZDKrIp0xdxiDNcwlZDgpup81nBHKy65zyiNdtdTQQB/NQ0Z4I0Dw1ENDcOKZkuyVPQklrLcOeSk9Asc3+KdA3gzgaRZZ1GUN4Ts4lBki8BBM7RRYqbgjHfScUGpEasQ==

internal:
  administration:
    domain: http://administration-dev:8081
    user-validate: /v1/users/validate